### ISSUE TITLE
About yarock

### ISSUE THREAD

**Issue by david-geiger** [sebaro/Yarock#1]
Hi,

Is this git repository the main official source code for yarock?

If yes have you planned to create a release tarball with current head code?

Regards,
David (Mageia Linux packager)

**Comment by sebaro** [comment]
Hi David,

The official/original source code is on Launchpad. There's no activity there in the last 5 years.
You can try contacting the original developer to see what's the status of the project.

My fork/repository contains the port to Qt6 and the QtMultimedia backend.
I can create a tarball release if needed.

**Comment by david-geiger** [comment]
Yes It would be great to a tarball release :)

**Comment by sebaro** [comment]
Released 1.5.0.

**Comment by david-geiger** [comment]
Thank you!

Is it possible to port it to new taglib v2?

> /home/david/mgarepo/07_A_FAIRE/pango/trader/tdlib/GNOME/ldns/amarok/yarock/BUILD/Yarock-1.5.0/src/core/mediaitem/tag.cpp:716:28: error: 'AttachedPictureFrame' is not a member of 'TagLib::ID3v2'
  716 |             TagLib::ID3v2::AttachedPictureFrame *frame = dynamic_cast<TagLib::ID3v2::AttachedPictureFrame *>(*it);

**Comment by sebaro** [comment]
On Gentoo v2 is not available yet, I see they changed the headers, this header was included by asffile.h (asfpicture.h) now it's not.

This should be fixed if you include the header:
#include <taglib/attachedpictureframe.h>

**Comment by david-geiger** [comment]
Yes perfect adding #include <taglib/attachedpictureframe.h> fixes build with taglib 2.0!
